# ==============================
# KITTY CONFIG
# ==============================

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        17

# Cursor
cursor_shape beam
cursor_blink_interval 0.25
cursor_trail 1


# Window
window_padding_width 8
hide_window_decorations yes
remember_window_size yes

# Scrollback
scrollback_lines 10000

# ==============================
# COLORS
# ==============================

# ========================
# WINDOW APPEARANCE
# ========================
background_opacity 1
dynamic_background_opacity yes

# Background / foreground
background #1e1e2e
foreground #cdd6f4

# Cursor
cursor #cdd6f4

# Selection
selection_background #585b70
selection_foreground #cdd6f4

# ==============================
# ANSI COLORS
# ==============================

color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #f5c2e7
color6  #94e2d5
color7  #bac2de

color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8

# ==============================
# TERMINAL
# ==============================

enable_audio_bell no
visual_bell_duration 0
confirm_os_window_close 0

# ==============================
# URL
# ==============================

url_color #89b4fa
url_style curly

# ========================
# PERFORMANCE
# ========================
repaint_delay 10
input_delay 3
sync_to_monitor yes

# ==============================
# TAB BAR
# ==============================

tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground #cdd6f4
active_tab_background #313244
inactive_tab_foreground #a6adc8
inactive_tab_background #181825
